# -*- coding: utf-8 -*-
"""Emotion_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCaScDyKWep4RgADClwsz8NFnqp_VFOa

Emotion Recognition from Speech

Goal: Recognize human emotions (happy, sad, angry, calm, fearful, etc.)
from speech audio using extracted acoustic features (MFCCs) and a
deep-learning-style classifier.

IMPORTANT NOTE ON DATASET (please read):
This environment has no internet access to download real audio
datasets such as RAVDESS, TESS or EMO-DB, and no audio files were
provided. To still deliver a complete, runnable pipeline, this script
is built in two parts:

  PART A - "Real data" pipeline (recommended for your actual submission):
    - If you place RAVDESS/TESS .wav files in a folder called
      'speech_dataset/', this script will automatically load them,
      extract MFCC features using librosa, and train a model on the
      REAL audio.
    - Download RAVDESS here (free): https://zenodo.org/record/1188976
      Folder structure expected: speech_dataset/Actor_xx/*.wav
      (RAVDESS filename convention is used to extract emotion labels)

  PART B - Demo/fallback pipeline (runs automatically if no audio found):
    - Generates a synthetic MFCC-feature dataset that mimics the
      statistical structure of real speech-emotion features, so you
      can see the full ML pipeline (model training, evaluation,
      confusion matrix) working end-to-end.

For your final submission, run this with the real RAVDESS dataset in
the 'speech_dataset/' folder for genuine results.

Author: (Nusrat Jahan)
"""

import os
import glob
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

RAVDESS_EMOTION_MAP = {
    "01": "neutral", "02": "calm", "03": "happy", "04": "sad",
    "05": "angry", "06": "fearful", "07": "disgust", "08": "surprised"
}

N_MFCC = 40

def extract_features_from_file(file_path):
    """Extract MFCC (mean + std) features from a wav file using librosa."""
    import librosa
    y, sr = librosa.load(file_path, sr=None)
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=N_MFCC)
    return np.concatenate([mfccs.mean(axis=1), mfccs.std(axis=1)])

def load_real_dataset(folder="speech_dataset"):
    files = glob.glob(os.path.join(folder, "**", "*.wav"), recursive=True)
    if not files:
        return None, None

    X, y = [], []
    for f in files:
        try:
            parts = os.path.basename(f).split("-")
            emotion_code = parts[2]
            label = RAVDESS_EMOTION_MAP.get(emotion_code, "unknown")
            feats = extract_features_from_file(f)
            X.append(feats)
            y.append(label)
        except Exception as e:
            print(f"Skipping {f}: {e}")

    return np.array(X), np.array(y)

def generate_synthetic_dataset(n_per_class=150):
    """
    Creates a synthetic dataset that mimics MFCC mean+std feature vectors
    for several emotion classes. Each emotion is given a distinct
    'signature' pattern with added noise, so the classifier has a
    realistic (not trivial) task.
    """
    np.random.seed(42)
    emotions = ["neutral", "happy", "sad", "angry", "fearful", "calm"]
    n_features = N_MFCC * 2  # mean + std

    X, y = [], []
    for emotion in emotions:
        base = np.random.uniform(-30, 30, n_features)
        for _ in range(n_per_class):
            sample = base + np.random.normal(0, 6, n_features)
            X.append(sample)
            y.append(emotion)

    return np.array(X), np.array(y)

def main():
    X, y = load_real_dataset()

    if X is None:
        print("No 'speech_dataset/' folder with .wav files found.")
        print("Falling back to SYNTHETIC demo dataset (see header comments).\n")
        X, y = generate_synthetic_dataset()
    else:
        print(f"Loaded {len(X)} real audio samples from speech_dataset/\n")

    df_features = pd.DataFrame(X)
    df_features["label"] = y
    df_features.to_csv("task2_speech_features.csv", index=False)

    le = LabelEncoder()
    y_enc = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=42, stratify=y_enc
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # MLP (multi-layer perceptron) acts as our neural-network classifier,
    # analogous to a simple feed-forward network on top of MFCC features
    # (a step before moving to CNN/LSTM on raw spectrograms).
    model = MLPClassifier(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        max_iter=500,
        random_state=42
    )
    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)

    print(f"Test Accuracy: {acc:.4f}\n")
    print("Classification Report:")
    print(classification_report(y_test, y_pred, target_names=le.classes_))
    print("Confusion Matrix:")
    cm = pd.DataFrame(
        confusion_matrix(y_test, y_pred),
        index=le.classes_, columns=le.classes_
    )
    print(cm)
    cm.to_csv("task2_confusion_matrix.csv")


if __name__ == "__main__":
    main()